server:
  port: 8088
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
<<<<<<< HEAD
    username: root
    password: root
=======
    username: cos
    password: cos1234
>>>>>>> 9faf17c0aeefd54f9cb9ae04cc9c771a711e9868
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.id.new_generator_mappings: true    
  jackson:
    serialization:
      fail-on-empty-beans: false
<<<<<<< HEAD
=======
      
>>>>>>> 9faf17c0aeefd54f9cb9ae04cc9c771a711e9868
      